/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-west-2',
	aws_cognito_identity_pool_id:
		'us-west-2:4c22a34b-39f7-4eb8-986a-a734790e43aa',
	aws_cognito_region: 'us-west-2',
	aws_user_pools_id: 'us-west-2_3hl2bbF8g',
	aws_user_pools_web_client_id: '1drrmmat9k26e5u7l0075cf0nr',
	oauth: {},
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: ['EMAIL'],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: ['SMS'],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: []
	},
	aws_cognito_verification_mechanisms: ['EMAIL']
};

export default awsmobile;
